version: '3.8'

services:
  ca:
    build:
      context: ./scripts              # Adjust if Dockerfile is in a subdirectory like ./scripts
      dockerfile: Dockerfile  # Optional if file is named Dockerfile
    container_name: ca-server
    ports:
      - "443:443"             # Expose HTTPS
    volumes:
      - ./scripts/pki_system:/pki-system  # Persistent PKI data
      - ./scripts/certs:/app/certs    # Certs used by Flask (must include ECC cert and key)
    networks:
      - ca_net
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

networks:
  ca_net:
    driver: bridge
